remote_theme: pages-themes/minimal@v0.2.0
title: [Working with me]
description: [A guide to how I work and communicate to support effective teamwork and success]
# logo: /assets/img/logo.png
show_downloads: false
github:
  is_user_page: true
  owner_url: https://github.com/jpgmeyer
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme